### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by cinqdtun** [Quantizr/DungeonRoomsMod#13]
When trying to connect at Hypixel i get most of times java.lang.NullPointerException like this(not all of time) :
![2022-05-06_15 43 10](https://user-images.githubusercontent.com/58152963/167145316-6d6f7350-b7cc-48b8-b479-9b5d85634d6a.png)
This the output error in log : 
[15:39:36] [Thread-280/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[15:39:36] [Thread-280/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.quantizr.dungeonrooms.utils.Utils.checkForConflictingHotkeys(Utils.java:105)
[15:39:36] [Thread-280/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.quantizr.dungeonrooms.DungeonRooms.lambda$onServerConnect$8(DungeonRooms.java:211)
[15:39:36] [Thread-280/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at io.github.quantizr.dungeonrooms.DungeonRooms$$Lambda$352/334197898.run(Unknown Source)
[15:39:36] [Thread-280/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by cinqdtun** [comment]
Edit : Occurs only after the first connect, after disconnecting

**Comment by cinqdtun** [comment]
The issue has been fixed in the latest version
